version: '2'
services:
  elasticsearch:
    image: elasticsearch:7.3.2
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.2
    ports:
      - "5601:5601"

volumes:
  redis:
    external: false
